/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2025-05-02 09:38:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import promeet_web.dao.AdminDao;
import promeet_web.dao.*;
import promeet_web.beans.*;
import java.util.*;

public final class adminhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/pie_chart.jsp", Long.valueOf(1746177972360L));
    _jspx_dependants.put("/admin/contact_count.jsp", Long.valueOf(1746177497033L));
    _jspx_dependants.put("/common_html/all_css.html", Long.valueOf(1742493036175L));
    _jspx_dependants.put("/admin/admin_header.html", Long.valueOf(1744736002839L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("promeet_web.beans");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("promeet_web.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("promeet_web.dao.AdminDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Admin Dashboard</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css\" integrity=\"sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/ProMeet/images/promeet1.jpg\" class=\"rounded-circle\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ProMeet/css/style.css\">");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- FontAwesome for Icons -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Styling */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dashboard-title {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Admin Dashboard Layout */\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dashboard-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height:250px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dashboard-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            background: linear-gradient(135deg, #ff9a9e, #fad0c4);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dashboard-card i {\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dashboard-card p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-card i ,dashboard-card p {\r\n");
      out.write("        margin-top: 90px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .dashboard-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .dashboard-card {\r\n");
      out.write("                width: 90%;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<nav class=\"navbar navbar-expand-lg fixed-top custom-navbar\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <h2 class=\"navbar-brand\">\r\n");
      out.write("            <i class=\"fas fa-user-circle logo-icon\"></i> Admin Portal\r\n");
      out.write("        </h2>\r\n");
      out.write("\r\n");
      out.write("        <button   class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasDarkNavbar\" aria-controls=\"offcanvasDarkNavbar\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("        <!-- Offcanvas Menu -->\r\n");
      out.write("        <div class=\"offcanvas offcanvas-end custom-offcanvas\" tabindex=\"-1\" id=\"offcanvasDarkNavbar\"\r\n");
      out.write("            aria-labelledby=\"offcanvasDarkNavbarLabel\">\r\n");
      out.write("            <div class=\"offcanvas-header\">\r\n");
      out.write("                <h5 class=\"offcanvas-title\"><b>Hello Admin</b></h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("                    aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"offcanvas-body\">\r\n");
      out.write("                <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/adminhome.jsp\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_contact.jsp\"><i class=\"fas fa-portrait\"></i>\r\n");
      out.write("                            Contact List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_feedback.jsp\"><i class=\"far fa-smile\"></i>\r\n");
      out.write("                            Feedback List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_user.jsp\"><i class=\"fas fa-user\"></i> User List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_expert.jsp\"><i class=\"fas fa-user-tie\"></i>\r\n");
      out.write("                            Expert List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link logout-link\" href=\"/ProMeet/AdminLogout\"><i class=\"fa fa-sign-out\"></i>\r\n");
      out.write("                            Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- ð¹ Custom CSS for Navbar -->\r\n");
      out.write("<style>\r\n");
      out.write("    /* ð¥ Stylish Navbar */\r\n");
      out.write("    .custom-navbar {\r\n");
      out.write("        background: linear-gradient(to right, #1f1c2c, #535a7b);\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð·ï¸ Brand Logo & Name */\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo-icon {\r\n");
      out.write("        color: red;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð¨ Offcanvas (Side Menu) */\r\n");
      out.write("    .custom-offcanvas {\r\n");
      out.write("        background: #24252a;\r\n");
      out.write("        color: white;\r\n");
      out.write("        width: 250px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas-header {\r\n");
      out.write("        background: #16171b;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð Navbar Links */\r\n");
      out.write("    .nav-link {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        padding: 12px 15px;\r\n");
      out.write("        transition: all 0.3s ease-in-out;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link:hover {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ðª Logout Link */\r\n");
      out.write("    .logout-link {\r\n");
      out.write("        color: red;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logout-link:hover {\r\n");
      out.write("        background: rgba(255, 0, 0, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð± Navbar Toggle Button */\r\n");
      out.write("    .custom-toggler {\r\n");
      out.write("        border: none;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-toggler:focus {\r\n");
      out.write("        box-shadow: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð­ Responsive */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo-icon {\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"dashboard-title\">Admin Dashboard</h2>\r\n");
      out.write("<br>\r\n");
      out.write("        <div class=\"dashboard-container\">\r\n");
      out.write("            <!-- Manage Users -->\r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                <i class=\"fas fa-users\"></i>\r\n");
      out.write("                <p><a href=\"/ProMeet/admin/all_user.jsp\" style=\"text-decoration: none;\">Manage Users</a> </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Manage Experts -->\r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                <i class=\"fas fa-user-tie\"></i>\r\n");
      out.write("                <p><a href=\"/ProMeet/admin/all_expert.jsp\" style=\"text-decoration: none;\">Manage Experts</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- View Feedback -->\r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                <i class=\"fas fa-comments\"></i>\r\n");
      out.write("                <p><a href=\"/ProMeet/admin/all_feedback.jsp\" style=\"text-decoration: none;\">View Feedback</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Manage Appointments -->\r\n");
      out.write("            <div class=\"dashboard-card\">\r\n");
      out.write("                <i class=\"fas fa-calendar-check\"></i>\r\n");
      out.write("                <p><a href=\"/ProMeet/admin/all_contact.jsp\" style=\"text-decoration: none;\">Manage Contacts</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("</div>\r\n");
      out.write("<h3>Contact Graphs</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#monthlyChart {\r\n");
      out.write("  max-width: 400px;\r\n");
      out.write("  min-height: 350px;\r\n");
      out.write("  margin:20px;\r\n");
      out.write("  background-color: cyan;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

    AdminDao dao1 = new AdminDao();
    LinkedHashMap<String, Integer> yearMonthMap = dao1.getMonthlyContactCounts();

    String labels = "";
    String values = "";

    for (Map.Entry<String, Integer> entry : yearMonthMap.entrySet()) {
        labels += "'" + entry.getKey() + "',";   // e.g., '2025-01'
        values += entry.getValue() + ",";
    }

    // Remove trailing commas
    if (!labels.isEmpty()) labels = labels.substring(0, labels.length() - 1);
    if (!values.isEmpty()) values = values.substring(0, values.length() - 1);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"width: 100%; overflow-x: auto;\">\r\n");
      out.write("    <canvas id=\"monthlyChart\"></canvas>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("window.addEventListener('load', function () {\r\n");
      out.write("    const ctx1 = document.getElementById('monthlyChart').getContext('2d');\r\n");
      out.write("    new Chart(ctx1, {\r\n");
      out.write("        type: 'bar',\r\n");
      out.write("        data: {\r\n");
      out.write("            labels: [");
      out.print( labels );
      out.write("],\r\n");
      out.write("            datasets: [{\r\n");
      out.write("                label: 'Contacts per Month',\r\n");
      out.write("                data: [");
      out.print( values );
      out.write("],\r\n");
      out.write("                backgroundColor: 'rgba(54, 162, 235, 0.6)',\r\n");
      out.write("                borderColor: 'rgba(54, 162, 235, 1)',\r\n");
      out.write("                borderWidth: 1,\r\n");
      out.write("                maxBarThickness: 50\r\n");
      out.write("            }]\r\n");
      out.write("        },\r\n");
      out.write("        options: {\r\n");
      out.write("            scales: {\r\n");
      out.write("                x: {\r\n");
      out.write("                    categoryPercentage: 1.0,\r\n");
      out.write("                    barPercentage: 0.4\r\n");
      out.write("                },\r\n");
      out.write("                y: {\r\n");
      out.write("                    beginAtZero: true,\r\n");
      out.write("                    max: 10,\r\n");
      out.write("                    ticks: {\r\n");
      out.write("                        stepSize: 0.5\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<h3>Feedback Ratings</h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#pieChart {\r\n");
      out.write("  max-width: 400px;\r\n");
      out.write("  height: 180px;\r\n");
      out.write("  margin:20px;\r\n");
      out.write("  background-color: cyan;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    AdminDao dao = new AdminDao();
    HashMap<String, Integer> count_map = dao.count_rating();
    pageContext.setAttribute("feedbackData", count_map);

    Map<String, Integer> ratingData = (Map<String, Integer>) pageContext.getAttribute("feedbackData");
    System.out.println("On jsp  "+ratingData);
    int fiveStarCount = 0;
    int fourStarCount = 0;
    int threeStarCount = 0;
    int twoStarCount = 0;
    int oneStarCount = 0;

   
    	if (ratingData != null) {
    	    fiveStarCount = ratingData.getOrDefault("five_star", 0);
    	    fourStarCount = ratingData.getOrDefault("four_star", 0);
    	    threeStarCount = ratingData.getOrDefault("three_star", 0);
    	    twoStarCount = ratingData.getOrDefault("two_star", 0);
    	    oneStarCount = ratingData.getOrDefault("one_star", 0);
    	}

    

      out.write("\r\n");
      out.write("\r\n");
      out.write("<canvas id=\"pieChart\" ></canvas>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("const ctx = document.getElementById('pieChart').getContext('2d');\r\n");
      out.write("const pieChart = new Chart(ctx, {\r\n");
      out.write("    type: 'pie',\r\n");
      out.write("    data: {\r\n");
      out.write("        labels: ['5 Stars', '4 Stars', '3 Stars', '2 Stars', '1 Star'],\r\n");
      out.write("        datasets: [{\r\n");
      out.write("            label: 'Star Rating Distribution',\r\n");
      out.write("            data: [");
      out.print( fiveStarCount );
      out.write(',');
      out.write(' ');
      out.print( fourStarCount );
      out.write(',');
      out.write(' ');
      out.print( threeStarCount );
      out.write(',');
      out.write(' ');
      out.print( twoStarCount );
      out.write(',');
      out.write(' ');
      out.print( oneStarCount );
      out.write("],\r\n");
      out.write("            backgroundColor: [\r\n");
      out.write("                'rgba(255, 99, 132, 0.6)',  // 5 stars (red)\r\n");
      out.write("                'rgba(54, 162, 235, 0.6)',  // 4 stars (blue)\r\n");
      out.write("                'rgba(255, 206, 86, 0.6)',  // 3 stars (yellow)\r\n");
      out.write("                'rgba(75, 192, 192, 0.6)',  // 2 stars (green)\r\n");
      out.write("                'rgba(153, 102, 255, 0.6)'  // 1 star (purple)\r\n");
      out.write("            ],\r\n");
      out.write("            borderColor: [\r\n");
      out.write("                'rgba(255, 99, 132, 1)',\r\n");
      out.write("                'rgba(54, 162, 235, 1)',\r\n");
      out.write("                'rgba(255, 206, 86, 1)',\r\n");
      out.write("                'rgba(75, 192, 192, 1)',\r\n");
      out.write("                'rgba(153, 102, 255, 1)'\r\n");
      out.write("            ],\r\n");
      out.write("            borderWidth: 1\r\n");
      out.write("        }]\r\n");
      out.write("    },\r\n");
      out.write("    \r\n");
      out.write("    options: {\r\n");
      out.write("        responsive: false,\r\n");
      out.write("        layout: {\r\n");
      out.write("            padding: 20\r\n");
      out.write("        },\r\n");
      out.write("        radius: '100%',\r\n");
      out.write("        plugins: {\r\n");
      out.write("            legend: {\r\n");
      out.write("                position: 'bottom'\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
