/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2025-04-15 16:53:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import promeet_web.dao.*;
import promeet_web.beans.*;
import java.util.*;

public final class all_005ffeedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common_html/all_css.html", Long.valueOf(1742493036175L));
    _jspx_dependants.put("/admin/admin_header.html", Long.valueOf(1744736002839L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("promeet_web.beans");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("promeet_web.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Feedback Details</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css\" integrity=\"sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/ProMeet/images/promeet1.jpg\" class=\"rounded-circle\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ProMeet/css/style.css\">");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General Styling */\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #74ebd5, #acb6e5);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Container */\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Feedback Heading */\r\n");
      out.write("        .title {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Feedback Cards Layout */\r\n");
      out.write("        .feedback-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Individual Feedback Box */\r\n");
      out.write("        .feedback-box {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            width: 280px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feedback-box:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            background: linear-gradient(135deg, #ff9a9e, #fad0c4);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Text Styling Inside the Box */\r\n");
      out.write("        .feedback-box p {\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remark {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #ff4b5c;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rating {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #ffa502;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-name {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("            color: #40739e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .feedback-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .feedback-box {\r\n");
      out.write("                width: 90%;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<nav class=\"navbar navbar-expand-lg fixed-top custom-navbar\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <h2 class=\"navbar-brand\">\r\n");
      out.write("            <i class=\"fas fa-user-circle logo-icon\"></i> Admin Portal\r\n");
      out.write("        </h2>\r\n");
      out.write("\r\n");
      out.write("        <button   class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasDarkNavbar\" aria-controls=\"offcanvasDarkNavbar\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("        <!-- Offcanvas Menu -->\r\n");
      out.write("        <div class=\"offcanvas offcanvas-end custom-offcanvas\" tabindex=\"-1\" id=\"offcanvasDarkNavbar\"\r\n");
      out.write("            aria-labelledby=\"offcanvasDarkNavbarLabel\">\r\n");
      out.write("            <div class=\"offcanvas-header\">\r\n");
      out.write("                <h5 class=\"offcanvas-title\"><b>Hello Admin</b></h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("                    aria-label=\"Close\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"offcanvas-body\">\r\n");
      out.write("                <ul class=\"navbar-nav justify-content-end flex-grow-1 pe-3\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/adminhome.jsp\"><i class=\"fas fa-home\"></i> Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_contact.jsp\"><i class=\"fas fa-portrait\"></i>\r\n");
      out.write("                            Contact List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_feedback.jsp\"><i class=\"far fa-smile\"></i>\r\n");
      out.write("                            Feedback List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_user.jsp\"><i class=\"fas fa-user\"></i> User List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"/ProMeet/admin/all_expert.jsp\"><i class=\"fas fa-user-tie\"></i>\r\n");
      out.write("                            Expert List</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link logout-link\" href=\"/ProMeet/AdminLogout\"><i class=\"fa fa-sign-out\"></i>\r\n");
      out.write("                            Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- ð¹ Custom CSS for Navbar -->\r\n");
      out.write("<style>\r\n");
      out.write("    /* ð¥ Stylish Navbar */\r\n");
      out.write("    .custom-navbar {\r\n");
      out.write("        background: linear-gradient(to right, #1f1c2c, #535a7b);\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð·ï¸ Brand Logo & Name */\r\n");
      out.write("    .navbar-brand {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logo-icon {\r\n");
      out.write("        color: red;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð¨ Offcanvas (Side Menu) */\r\n");
      out.write("    .custom-offcanvas {\r\n");
      out.write("        background: #24252a;\r\n");
      out.write("        color: white;\r\n");
      out.write("        width: 250px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .offcanvas-header {\r\n");
      out.write("        background: #16171b;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð Navbar Links */\r\n");
      out.write("    .nav-link {\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        padding: 12px 15px;\r\n");
      out.write("        transition: all 0.3s ease-in-out;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-link:hover {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ðª Logout Link */\r\n");
      out.write("    .logout-link {\r\n");
      out.write("        color: red;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logout-link:hover {\r\n");
      out.write("        background: rgba(255, 0, 0, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð± Navbar Toggle Button */\r\n");
      out.write("    .custom-toggler {\r\n");
      out.write("        border: none;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .custom-toggler:focus {\r\n");
      out.write("        box-shadow: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ð­ Responsive */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .logo-icon {\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"title\">User Feedback & Ratings</h2>\r\n");
      out.write("\r\n");
      out.write("        ");

        AdminDao dao = new AdminDao();
        ArrayList<Feedback> feedbackList = dao.viewAllFeedback();
        if (feedbackList.size() > 0) {
        
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"feedback-container\">\r\n");
      out.write("            ");
 for (Feedback f : feedbackList) { 
      out.write("\r\n");
      out.write("            <div class=\"feedback-box\">\r\n");
      out.write("                <p class=\"remark\">\"");
      out.print( f.getRemark() );
      out.write("\"</p>\r\n");
      out.write("                <p class=\"rating\">⭐ Rating: ");
      out.print( f.getRating() );
      out.write(" / 5</p>\r\n");
      out.write("                <p class=\"user-name\">🙍‍♂️ Given By: ");
      out.print( f.getName() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <p style=\"color: white; font-size: 20px;\">No feedback available at the moment.</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("        integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
