/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2025-04-22 09:05:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fregistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/common/navbar.html", Long.valueOf(1745050903321L));
    _jspx_dependants.put("/WEB-INF/common/footer.html", Long.valueOf(1742493861481L));
    _jspx_dependants.put("/common_html/all_css.html", Long.valueOf(1742493036175L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>User Registration</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css\" integrity=\"sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/ProMeet/images/promeet1.jpg\" class=\"rounded-circle\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ProMeet/css/style.css\">");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap Icons (Optional) -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(135deg, #1c1c1c, #3a3a3a);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .main-container {\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control, .form-select {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control::placeholder {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-control:focus, .form-select:focus {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("            border: 1px solid #6c63ff;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(108, 99, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-submit {\r\n");
      out.write("            background: #6c63ff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-submit:hover {\r\n");
      out.write("            background: #5248d0;\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .alert-custom {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .main-container:hover {\r\n");
      out.write("    box-shadow: 0px 0px 30px rgba(108, 99, 255, 0.5);\r\n");
      out.write("    transition: box-shadow 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js\" integrity=\"sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function checkAlpha(event)\r\n");
      out.write("    {\r\n");
      out.write("    console.log(event)// it is an object -> property -> value and functions\r\n");
      out.write("    let data=event.target.value\r\n");
      out.write("    //alert(data)\r\n");
      out.write("    //const regex = /^[a-z ]*$/i; /\r\n");
      out.write("    const regEx=/^[a-zA-Z ]*$/			//^means start of string and$means End * means 0 or more times\r\n");
      out.write("    if(!regEx.test(data))\r\n");
      out.write("    {\r\n");
      out.write("    event.target.value=data.replace(/[^a-zA-Z ]/g, '');//^means apart from these charachers\r\n");
      out.write("    /* alert(\"only alphabets are allowed \") */\r\n");
      out.write("    Swal.fire({\r\n");
      out.write("    	  title: \"Format Error\",\r\n");
      out.write("    	  text: \"Only Alphabets Are Allowed\",\r\n");
      out.write("    	  icon: \"error\"\r\n");
      out.write("    	});\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    }//check Alpha Close\r\n");
      out.write("    function checkDigit(event) {\r\n");
      out.write("        let data = event.target.value;\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("        if (event.key === \"Backspace\" || event.key === \"Delete\" || event.key === \"ArrowLeft\" || event.key === \"ArrowRight\") {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        if (data.length >= 10 && event.key !== \"Backspace\" && event.key !== \"Delete\") {\r\n");
      out.write("            /* alert(\"Only 10 digits are allowed\"); */\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("    	  title: \"Format Error\",\r\n");
      out.write("    	  text: \"Only 10 Digit Are Allowed\",\r\n");
      out.write("    	  icon: \"error\"\r\n");
      out.write("    	});\r\n");
      out.write("            event.preventDefault();  \r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        const regEx = /^[0-9]*$/;\r\n");
      out.write("        if (!regEx.test(data + event.key)) {\r\n");
      out.write("            /* alert(\"Only digits are allowed\"); */\r\n");
      out.write("            Swal.fire({\r\n");
      out.write("    	  title: \"Format Error\",\r\n");
      out.write("    	  text: \"Only Digit Are Allowed\",\r\n");
      out.write("    	  icon: \"error\"\r\n");
      out.write("    	});\r\n");
      out.write("            event.preventDefault();  \r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	\r\n");
      out.write("    	$(\"#email\").change(function(){\r\n");
      out.write("\r\n");
      out.write("    		 let userEmail=$(this).val()\r\n");
      out.write("    		    //alert(userEmail)\r\n");
      out.write("    	\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write(" $.ajax({\r\n");
      out.write("\r\n");
      out.write("	url:\"/ProMeet/User_Registration\",\r\n");
      out.write("	type:\"GET\",\r\n");
      out.write("	data:{\"uEmail\":userEmail},\r\n");
      out.write("	success:function(responseData){\r\n");
      out.write("    //alert(responseData)\r\n");
      out.write("	if(responseData==\"true\")\r\n");
      out.write("		{\r\n");
      out.write("	$(\"#ajaxMsg\").text(\"User Email already exists \")\r\n");
      out.write("	//alert(userEmail + \"already exists\")\r\n");
      out.write("		setTimeout(function(){\r\n");
      out.write("\r\n");
      out.write("		$(\"#email\").val(\"\")\r\n");
      out.write("	    $(\"#ajaxMsg\").text(\"\")\r\n");
      out.write("		},3000)\r\n");
      out.write("		}//if close\r\n");
      out.write("	}//success  object function close\r\n");
      out.write("\r\n");
      out.write(" })//ajax fucntion close\r\n");
      out.write("    		    \r\n");
      out.write("  \r\n");
      out.write(" })//on change close\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("    })//documentReady close\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover{\r\n");
      out.write("color:red;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-link,.nav-item dropdown{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("font-size:1rem;\r\n");
      out.write("font-family: sans-serif;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".dropdown-item{\r\n");
      out.write("\r\n");
      out.write("color:red;\r\n");
      out.write("font-size:1rem;\r\n");
      out.write("font-family: sans-serif;\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\" style=\"background-color:black; \" >\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\"><img src=\"/ProMeet/images/download.jpg\" alt=\"\" width=\"30\" height=\"24\" class=\"rounded-circle\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" >\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\" >\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"/ProMeet/jsp/index.jsp\">\r\n");
      out.write("          \r\n");
      out.write("          <i class=\"fas fa-home\" style=\"color:white\"> </i></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"/ProMeet/jsp/aboutus.jsp\">AboutUs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"/ProMeet/jsp/contact_us.jsp\">ContactUs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Registration\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/user/user_registration.jsp\">User</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/expert/expert.jsp\">Expert</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Login\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/user/user_login.jsp\">User</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/expert/expert_login.jsp\">Expert</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("      </form> -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 String mess = (String) request.getAttribute("message"); 
      out.write("\r\n");
      out.write("    ");
 if (mess != null) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-info alert-dismissible fade show text-center alert-custom mt-3 mx-auto w-50\" role=\"alert\">\r\n");
      out.write("        <strong>");
      out.print( mess );
      out.write("</strong>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container d-flex justify-content-center\">\r\n");
      out.write("        <div class=\"main-container\">\r\n");
      out.write("            <h2 class=\"text-center text-white mb-4\">📝 User Registration</h2>\r\n");
      out.write("            <form action=\"/ProMeet/User_Registration\" method=\"post\" class=\"needs-validation\" enctype=\"multipart/form-data\" novalidate>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"far fa-envelope\"></i> Email-ID</label>\r\n");
      out.write("                    <input type=\"email\" name=\"email\" id=\"email\" class=\"form-control\" placeholder=\"Enter Email\" required>\r\n");
      out.write("                    <span id=\"ajaxMsg\" style=\"color:red; \"></span>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide your email.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"fas fa-lock\"></i> Password</label>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Enter Password\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide your password.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"far fa-user\"></i> Name</label>\r\n");
      out.write("                    <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"Enter Name\" required  oninput=\"checkAlpha(event)\">\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide your name.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"fas fa-phone-alt\"></i> Phone</label>\r\n");
      out.write("                    <input type=\"tel\" name=\"phone\" class=\"form-control\" placeholder=\"Enter Phone Number\" required  onkeydown=checkDigit(event)    maxlength=\"10\"  >\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide your phone number.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\" >\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"fas fa-city\"></i> City</label>\r\n");
      out.write("                    <select name=\"city\" class=\"form-select\" style=\"background: rgba(255, 255, 255, 0.1);\" required>\r\n");
      out.write("                        <option  value=\"\" selected disabled>Select City</option>\r\n");
      out.write("                        <option value=\"Azamgarh\">Azamgarh</option>\r\n");
      out.write("                        <option value=\"Lucknow\">Lucknow</option>\r\n");
      out.write("                        <option value=\"Patna\">Patna</option>\r\n");
      out.write("                        <option value=\"Mumbai\">Mumbai</option>\r\n");
      out.write("                        <option value=\"Noida\">Noida</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please select your city.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"fas fa-map-marker-alt\"></i> Address</label>\r\n");
      out.write("                    <textarea class=\"form-control\" name=\"address\" rows=\"3\" placeholder=\"Enter your address\" required></textarea>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please provide your address.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label class=\"form-label\"><i class=\"far fa-image\"></i> Profile Picture</label>\r\n");
      out.write("                    <input type=\"file\" class=\"form-control\" name=\"profilePic\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Please upload a profile picture.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-submit\"><i class=\"fas fa-user-check\"></i> Register</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    // Fade in the registration form\r\n");
      out.write("    $(\".main-container\").hide().fadeIn(1000);\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    $(\".form-control, .form-select, textarea\").on(\"focus\", function () {\r\n");
      out.write("        $(this).css({\r\n");
      out.write("            \"transform\": \"scale(1.02)\",\r\n");
      out.write("            \"transition\": \"transform 0.2s ease-in-out\"\r\n");
      out.write("        });\r\n");
      out.write("    }).on(\"blur\", function () {\r\n");
      out.write("        $(this).css(\"transform\", \"scale(1)\");\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(\".alert\").hide().fadeIn(800).delay(3000).fadeOut(1000);\r\n");
      out.write("\r\n");
      out.write("    // Submit button hover glow effect\r\n");
      out.write("    $(\".btn-submit\").hover(\r\n");
      out.write("        function () {\r\n");
      out.write("            $(this).css({\r\n");
      out.write("                \"box-shadow\": \"0 0 15px rgba(108, 99, 255, 0.8)\",\r\n");
      out.write("                \"letter-spacing\": \"1px\"\r\n");
      out.write("            });\r\n");
      out.write("        },\r\n");
      out.write("        function () {\r\n");
      out.write("            $(this).css({\r\n");
      out.write("                \"box-shadow\": \"none\",\r\n");
      out.write("                \"letter-spacing\": \"normal\"\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <script src=\"/ProMeet/js/validation.js\"></script>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    ");
      out.write("<footer class=\" text-center\" style=\"background-color: cyan\">\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("  <div class=\"container p-4 pb-0\">\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("    <section class=\"mb-4\">\r\n");
      out.write("      <!-- Facebook -->\r\n");
      out.write("      <a\r\n");
      out.write("      data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #3b5998;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-facebook-f\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Twitter -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #55acee;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Google -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #dd4b39;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-google\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Instagram -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #ac2bac;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Linkedin -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #0082ca;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-linkedin-in\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Github -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #333333;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-github\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgb(0, 0, 64); color:red;\">\r\n");
      out.write("    Â© 2025 Copyright Created By Prince\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
