/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2025-04-29 09:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/common/navbar.html", Long.valueOf(1745050903321L));
    _jspx_dependants.put("/WEB-INF/common/footer.html", Long.valueOf(1742493861481L));
    _jspx_dependants.put("/common_html/all_css.html", Long.valueOf(1742493036175L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>About Us - ProMeet</title>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css\" integrity=\"sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/ProMeet/images/promeet1.jpg\" class=\"rounded-circle\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ProMeet/css/style.css\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome for Icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Background Gradient */\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(45deg, #001f3f, #003366, #004080);\r\n");
      out.write("            background-size: 300% 300%;\r\n");
      out.write("            animation: gradientAnimation 8s infinite alternate;\r\n");
      out.write("            font-family: \"Poppins\", sans-serif;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-top: 80px; /* Space for fixed navbar */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes gradientAnimation {\r\n");
      out.write("            0% { background-position: 0% 50%; }\r\n");
      out.write("            100% { background-position: 100% 50%; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Fixed Top Navbar */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.8);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* About Us Section */\r\n");
      out.write("        .about-section {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0px 6px 18px rgba(0, 128, 255, 0.5);\r\n");
      out.write("            transition: transform 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            box-shadow: 0px 10px 30px rgba(0, 128, 255, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-title {\r\n");
      out.write("            font-size: 2.8rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #00ccff; /* Light blue */\r\n");
      out.write("            text-shadow: 2px 2px 10px rgba(0, 204, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive About Image */\r\n");
      out.write("        .about-img {\r\n");
      out.write("            width: 220px;\r\n");
      out.write("            height: 220px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            box-shadow: 0px 8px 20px rgba(0, 128, 255, 0.6);\r\n");
      out.write("            transition: transform 0.4s ease-in-out, box-shadow 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-img:hover {\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("            box-shadow: 0px 15px 30px rgba(0, 128, 255, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Contact Button */\r\n");
      out.write("        .contact-btn {\r\n");
      out.write("            background: linear-gradient(45deg, #0066ff, #00ccff);\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            color: black;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease-in-out;\r\n");
      out.write("            box-shadow: 0px 4px 10px rgba(0, 128, 255, 0.5);\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contact-btn:hover {\r\n");
      out.write("            background: linear-gradient(45deg, #00ccff, #0066ff);\r\n");
      out.write("            transform: scale(1.1);\r\n");
      out.write("            box-shadow: 0px 8px 20px rgba(0, 128, 255, 0.8);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* About Illustration */\r\n");
      out.write("        .illustration-img {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0px 6px 18px rgba(0, 128, 255, 0.5);\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .about-img {\r\n");
      out.write("                width: 180px;\r\n");
      out.write("                height: 180px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Fixed Navbar -->\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover{\r\n");
      out.write("color:red;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-link,.nav-item dropdown{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("font-size:1rem;\r\n");
      out.write("font-family: sans-serif;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".dropdown-item{\r\n");
      out.write("\r\n");
      out.write("color:red;\r\n");
      out.write("font-size:1rem;\r\n");
      out.write("font-family: sans-serif;\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\" style=\"background-color:black; \" >\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\"><img src=\"/ProMeet/images/download.jpg\" alt=\"\" width=\"30\" height=\"24\" class=\"rounded-circle\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" >\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\" >\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"/ProMeet/jsp/index.jsp\">\r\n");
      out.write("          \r\n");
      out.write("          <i class=\"fas fa-home\" style=\"color:white\"> </i></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"/ProMeet/jsp/aboutus.jsp\">AboutUs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"/ProMeet/jsp/contact_us.jsp\">ContactUs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Registration\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/user/user_registration.jsp\">User</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/expert/expert.jsp\">Expert</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Login\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/user/user_login.jsp\">User</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/expert/expert_login.jsp\">Expert</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("      </form> -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- About Us Section -->\r\n");
      out.write("<div class=\"container my-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-10 about-section text-center\">\r\n");
      out.write("            <h1 class=\"about-title\">ABOUT US</h1>\r\n");
      out.write("            <p class=\"lead\">\r\n");
      out.write("                <img class=\"about-img\" src=\"/ProMeet/images/promeet1.jpg\" alt=\"ProMeet Logo\">\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                Welcome to <strong>ProMeet</strong>, a cutting-edge platform that redefines professional networking.\r\n");
      out.write("                In today's fast-paced world, meaningful connections are crucial. Our goal is to create an ecosystem where\r\n");
      out.write("                professionals across industries can <strong>collaborate, learn, and grow</strong> together.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <h2>🚀 Our Vision</h2>\r\n");
      out.write("            <p>\r\n");
      out.write("                To be the leading professional networking hub, fostering a diverse and collaborative environment\r\n");
      out.write("                where individuals can find opportunities, resources, and support for their career growth.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <h3>🔹 What We Offer</h3>\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><i class=\"fa fa-users\"></i> **Global Networking** - Connect with professionals worldwide.</li>\r\n");
      out.write("                <li><i class=\"fa fa-chalkboard-teacher\"></i> **Learning & Development** - Webinars & expert talks.</li>\r\n");
      out.write("                <li><i class=\"fa fa-briefcase\"></i> **Job & Business Opportunities** - Find career-changing deals.</li>\r\n");
      out.write("                <li><i class=\"fa fa-lightbulb\"></i> **Innovative Career Growth Tools** - Personalized recommendations.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <h3>🌟 Why Choose ProMeet?</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                Unlike traditional networking platforms, **ProMeet is built for real engagement**—not just business card exchanges.\r\n");
      out.write("                Whether you’re looking for **mentorship, partnerships, or inspiration**, we provide the tools to help you **flourish**.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <!-- Contact Button -->\r\n");
      out.write("            <a href=\"/ProMeet/jsp/contact_us.jsp\" style=\"text-decoration: none;\">\r\n");
      out.write("            <button class=\"btn contact-btn\">\r\n");
      out.write("                <i class=\"fa fa-envelope\"></i> CONTACT US\r\n");
      out.write("            </button>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- About Illustration -->\r\n");
      out.write("            <div>\r\n");
      out.write("                <img class=\"illustration-img\" src=\"/ProMeet/images/depositphotos_167005130-stock-photo-businessman-touching-word-screen-digital.jpg\" alt=\"Professional Networking\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    // Fade in the entire about section\r\n");
      out.write("    $(\".about-section\").hide().fadeIn(1500);\r\n");
      out.write("\r\n");
      out.write("    // Fade in the logo image with a delay\r\n");
      out.write("    $(\".about-img\").hide().delay(500).fadeIn(1500);\r\n");
      out.write("\r\n");
      out.write("    // Fade in the illustration image with a longer delay\r\n");
      out.write("    $(\".illustration-img\").hide().delay(500).fadeIn(1500);\r\n");
      out.write("\r\n");
      out.write("    // Scroll effect to change heading color\r\n");
      out.write("    $(window).on('scroll', function () {\r\n");
      out.write("        let scrollTop = $(this).scrollTop();\r\n");
      out.write("        if (scrollTop > 50) {\r\n");
      out.write("            $(\".about-title\").css({\r\n");
      out.write("                \"color\": \"#ffcc00\",\r\n");
      out.write("                \"text-shadow\": \"2px 2px 10px rgba(255, 204, 0, 0.7)\"\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            $(\".about-title\").css({\r\n");
      out.write("                \"color\": \"#00ccff\",\r\n");
      out.write("                \"text-shadow\": \"2px 2px 10px rgba(0, 204, 255, 0.6)\"\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Hover effect on contact button\r\n");
      out.write("    $(\".contact-btn\").hover(\r\n");
      out.write("        function () {\r\n");
      out.write("            $(this).css(\"letter-spacing\", \"2px\");\r\n");
      out.write("        },\r\n");
      out.write("        function () {\r\n");
      out.write("            $(this).css(\"letter-spacing\", \"normal\");\r\n");
      out.write("        }\r\n");
      out.write("    );\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\" text-center\" style=\"background-color: cyan\">\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("  <div class=\"container p-4 pb-0\">\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("    <section class=\"mb-4\">\r\n");
      out.write("      <!-- Facebook -->\r\n");
      out.write("      <a\r\n");
      out.write("      data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #3b5998;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-facebook-f\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Twitter -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #55acee;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Google -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #dd4b39;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-google\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Instagram -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #ac2bac;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Linkedin -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #0082ca;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-linkedin-in\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Github -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #333333;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-github\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgb(0, 0, 64); color:red;\">\r\n");
      out.write("    Â© 2025 Copyright Created By Prince\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
