/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2025-04-19 16:17:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import promeet_web.dao.*;
import promeet_web.beans.*;
import java.util.*;
import ProMeet.utilities.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/common/navbar.html", Long.valueOf(1745050903321L));
    _jspx_dependants.put("/WEB-INF/common/footer.html", Long.valueOf(1742493861481L));
    _jspx_dependants.put("/common_html/all_css.html", Long.valueOf(1742493036175L));
    _jspx_dependants.put("/WEB-INF/common/carousel.html", Long.valueOf(1744721469389L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("promeet_web.beans");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("ProMeet.utilities");
    _jspx_imports_packages.add("promeet_web.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Main Page</title>\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("h1 {\r\n");
      out.write("    font-family: 'Roboto' 	;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("      /* Bold weight */\r\n");
      out.write("}\r\n");
      out.write(".div-items{\r\n");
      out.write("width:20%;\r\n");
      out.write("height:200px;\r\n");
      out.write("background-color: red;\r\n");
      out.write("margin-left: 2%;\r\n");
      out.write("border-radius: 20px;\r\n");
      out.write("margin-top: 30px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("    .feedback-section {\r\n");
      out.write("        background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("        box-shadow: 0px 10px 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        margin-bottom: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-card {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("        backdrop-filter: blur(15px);\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        transition: transform 0.3s ease;\r\n");
      out.write("        	\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-card:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-img img {\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height: 80px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        border: 3px solid #fff;\r\n");
      out.write("        box-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-content h5 {\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stars {\r\n");
      out.write("        color: #ffdd00;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-content p {\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".feedback-card1 {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("        backdrop-filter: blur(15px);\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        transition: transform 0.3s ease-in-out, box-shadow 0.3s ease-in-out;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        transition: transform 0.3s ease;\r\n");
      out.write("        	\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-card1:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("        box-shadow: 0 8px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".gradient-header {\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    font-size: 3rem;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    background: linear-gradient(90deg, #00f0ff, #7b2ff7, #f107a3);\r\n");
      out.write("    -webkit-background-clip: text;\r\n");
      out.write("    -webkit-text-fill-color: transparent;\r\n");
      out.write("    animation: typing 4s steps(30, end) forwards, blink 0.75s step-end infinite;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    border-right: 3px solid #00f0ff;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    text-shadow: 0 0 10px rgba(0,255,255,0.3), 0 0 20px rgba(255,0,255,0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes typing {\r\n");
      out.write("    from { width: 0 }\r\n");
      out.write("    to { width: 100% }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes blink {\r\n");
      out.write("    50% { border-color: transparent; }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    .feedback-content h5 {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 1.1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-content p {\r\n");
      out.write("        font-style: italic;\r\n");
      out.write("        font-size: 0.95rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feedback-date {\r\n");
      out.write("        font-size: 0.85rem;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        opacity: 0.8;\r\n");
      out.write("    }\r\n");
      out.write(".scrolling-container {\r\n");
      out.write("    height: 300px; /* Adjust height as needed */\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#scrollContent {\r\n");
      out.write("    animation: scrollUp 10s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@keyframes scrollUp {\r\n");
      out.write("    0% {\r\n");
      out.write("        transform: translateY(0%);\r\n");
      out.write("    }\r\n");
      out.write("    100% {\r\n");
      out.write("        transform: translateY(-100%);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Feedback Card Styling */\r\n");
      out.write(".feedback-card1 {\r\n");
      out.write("    background: #2a4a8c;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("let colors=[\"RED\",\"GREEN\",\"BLUE\"]\r\n");
      out.write("let idx=0\r\n");
      out.write("function changeColor()\r\n");
      out.write("{\r\n");
      out.write("let tg=document.getElementById(\"msg\")\r\n");
      out.write("tg.style.color=colors[idx]\r\n");
      out.write("idx++\r\n");
      out.write("if (idx>2)\r\n");
      out.write("	idx=0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("setInterval(changeColor,1000)\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css\" integrity=\"sha512-q3eWabyZPc1XTCmF+8/LuE1ozpg5xxn7iO89yfSOd5/oKvyqLngoNGsx8jq92Y8eXJ/IRxQbEC+FGSYxtk2oiw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"/ProMeet/images/promeet1.jpg\" class=\"rounded-circle\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ProMeet/css/style.css\">");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main-body\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <h1 class=\"gradient-header\">ProMeet Welcomes You</h1>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover{\r\n");
      out.write("color:red;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".nav-link,.nav-item dropdown{\r\n");
      out.write("\r\n");
      out.write("color:white;\r\n");
      out.write("font-size:1rem;\r\n");
      out.write("font-family: sans-serif;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".dropdown-item{\r\n");
      out.write("\r\n");
      out.write("color:red;\r\n");
      out.write("font-size:1rem;\r\n");
      out.write("font-family: sans-serif;\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg\" style=\"background-color:black; \" >\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\"><img src=\"/ProMeet/images/download.jpg\" alt=\"\" width=\"30\" height=\"24\" class=\"rounded-circle\">\r\n");
      out.write("    </a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\" >\r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\" >\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"/ProMeet/jsp/index.jsp\">\r\n");
      out.write("          \r\n");
      out.write("          <i class=\"fas fa-home\" style=\"color:white\"> </i></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"/ProMeet/jsp/aboutus.jsp\">AboutUs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"/ProMeet/jsp/contact_us.jsp\">ContactUs</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Registration\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/user/user_registration.jsp\">User</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/expert/expert.jsp\">Expert</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Login\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/user/user_login.jsp\">User</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"/ProMeet/expert/expert_login.jsp\">Expert</a></li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\r\n");
      out.write("      </form> -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".w-100{\r\n");
      out.write("height:80vh;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("  <div class=\"carousel-indicators\">\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"/ProMeet/images/meeting.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"/ProMeet/images/m4.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"/ProMeet/images/m3.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- feedback Code Here -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container my-5 feedback-section\">\r\n");
      out.write("    <h2 class=\"text-center text-white mb-4\">💬 What Our Users FeedBack</h2>\r\n");
      out.write("    <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("        ");
 GuestDao dao = new GuestDao();
        ArrayList<User> userList = dao.allFeedbacks();
        for (User u : userList) {
            String picName = u.getProfile_pic();
            String picPath = request.getContextPath() + "/" + picName;
            Feedback f = u.getFd(); // Feedback object
            String rating = f.getRating();
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Feedback Card -->\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 mb-4\">\r\n");
      out.write("            <div class=\"feedback-card\">\r\n");
      out.write("                <div class=\"feedback-img\">\r\n");
      out.write("                    <img src=\"");
      out.print(picPath);
      out.write("\" alt=\"User Pic\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"feedback-content\">\r\n");
      out.write("                    <h5>");
      out.print( f.getName() );
      out.write("</h5>\r\n");
      out.write("                    <p class=\"stars\">");
      out.print( rating );
      out.write("</p>\r\n");
      out.write("                    <p>\"");
      out.print( f.getRemark() );
      out.write("\"</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container my-5 feedback-section\">\r\n");
      out.write("    <h2 class=\"text-center text-white mb-4\">💬 What Our Expert Tips</h2>\r\n");
      out.write("\r\n");
      out.write("    <!-- Scrollable Container -->\r\n");
      out.write("    <div class=\"scrolling-container\" id=\"autoScrollBox\">\r\n");
      out.write("        <div class=\"row flex-column\" id=\"scrollContent\">\r\n");
      out.write("            ");

                GuestDao dao1 = new GuestDao();
                ArrayList<Expert> expertList = dao1.allTips();
                for (Expert e : expertList) {
                    Tips t = e.getTips();
            
      out.write("\r\n");
      out.write("                <div class=\"col-lg-12 mb-3\">\r\n");
      out.write("                    <div class=\"feedback-card1\">\r\n");
      out.write("                        <div class=\"feedback-content\">\r\n");
      out.write("                            <h5>Posted By: ");
      out.print( e.getName() );
      out.write("</h5>\r\n");
      out.write("                            <p>\"");
      out.print( t.getContent() );
      out.write("\"</p>\r\n");
      out.write("                            <small>");
      out.print( t.getDate() );
      out.write("</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const scrollBox = document.getElementById('autoScrollBox');\r\n");
      out.write("    const scrollContent = document.getElementById('scrollContent');\r\n");
      out.write("\r\n");
      out.write("    scrollBox.addEventListener('mouseenter', () => {\r\n");
      out.write("        scrollContent.style.animationPlayState = 'paused';\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    scrollBox.addEventListener('mouseleave', () => {\r\n");
      out.write("        scrollContent.style.animationPlayState = 'running';\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<footer class=\" text-center\" style=\"background-color: cyan\">\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("  <div class=\"container p-4 pb-0\">\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("    <section class=\"mb-4\">\r\n");
      out.write("      <!-- Facebook -->\r\n");
      out.write("      <a\r\n");
      out.write("      data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #3b5998;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-facebook-f\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Twitter -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #55acee;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Google -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #dd4b39;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-google\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Instagram -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #ac2bac;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Linkedin -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #0082ca;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-linkedin-in\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("      <!-- Github -->\r\n");
      out.write("      <a\r\n");
      out.write("        data-mdb-ripple-init\r\n");
      out.write("        class=\"btn text-white btn-floating m-1\"\r\n");
      out.write("        style=\"background-color: #333333;\"\r\n");
      out.write("        href=\"#!\"\r\n");
      out.write("        role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-github\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgb(0, 0, 64); color:red;\">\r\n");
      out.write("    Â© 2025 Copyright Created By Prince\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
